# Generated by Django 4.2.4 on 2023-09-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.commentmodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
