# Generated by Django 4.2.4 on 2023-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentmodel_parent_alter_commentmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='post_id',
            field=models.BigIntegerField(),
        ),
    ]
