# Generated by Django 4.2.4 on 2023-09-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_commentmodel_post_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('user_id', 'comment_id')},
            },
        ),
    ]
