# Generated by Django 4.2.4 on 2023-09-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_commentmodel_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
