# Generated by Django 4.2.4 on 2023-09-08 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MessageToSupport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Spam', 'Спам'), ('Affront', 'Оскорбление'), ('Law violation', 'Нарушение закона'), ('Pornographic content', 'Порнографический контент'), ('Violence', 'Насилие'), ('Copyright', 'Авторские права'), ('Other', 'Другое')], max_length=64)),
                ('message', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('date_to_send', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
