# Generated by Django 4.2.4 on 2023-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_helparticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetosupport',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
