# Generated by Django 4.2.4 on 2023-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_messagetosupport_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetosupport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MessagesImage/'),
        ),
    ]
