# Generated by Django 4.2.4 on 2023-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_messagetosupport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helparticle',
            name='image',
        ),
        migrations.AddField(
            model_name='messagetosupport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
