# Generated by Django 4.2.4 on 2023-10-20 20:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_remove_helparticle_image_messagetosupport_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplainPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('date_to_send', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.BigIntegerField()),
                ('post_id', models.BigIntegerField()),
                ('complain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.complain')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageToSupport',
        ),
    ]
