# Generated by Django 4.2.4 on 2023-10-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_complain_complainpost_delete_messagetosupport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainpost',
            name='complain_type',
        ),
        migrations.AddField(
            model_name='complainpost',
            name='complain_types',
            field=models.ManyToManyField(related_name='complain_posts', to='support.complain'),
        ),
    ]
