# Generated by Django 4.2.4 on 2023-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
