# Generated by Django 4.2.4 on 2023-09-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
