# Generated by Django 4.2.4 on 2023-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
