# Generated by Django 4.2.4 on 2023-10-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmodel_like_count_alter_likemodel_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likemodel',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='FavoriteModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postmodel')),
            ],
            options={
                'unique_together': {('user_id', 'post_id')},
            },
        ),
    ]
