# Generated by Django 4.2.4 on 2023-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_author_name_postmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
