version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: microblog_support
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      DJANGO_SECRET_KEY: django-insecure-_780k3^!bthvp&h36ir_33gtv@f(b+hlu(eu6%fj#tr)wyyzs4
      DJANGO_ENABLE_DEBUG: 1
      MAIL_MICROSERVICE_URL: 'http://localhost:8081/'
      USERS_MICROSERVICE_URL: 'http://localhost:8080/'
      POSTS_MICROSERVICE_URL: 'http://localhost:8082/'
      COMMENTS_MICROSERVICE_URL: 'http://localhost:8083/'
      SUPPORT_MICROSERVICE_URL: 'http://localhost:8084/'
    ports:
      - "8084:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    privileged: true
    restart: "on-failure"
    environment:
      POSTGRES_DB: microblog_support
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass

volumes:
  postgres_data:
