version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: microblog_posts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      DJANGO_SECRET_KEY: django-insecure-c6k*cu!9(vbuoh6!bwo#su2(5(^nqto6mu26+9n@4md*r9vg&@
      DJANGO_ENABLE_DEBUG: 1
      MAIL_MICROSERVICE_URL: 'http://localhost:8081/'
      USERS_MICROSERVICE_URL: 'http://localhost:8080/'
      POSTS_MICROSERVICE_URL: 'http://localhost:8082/'
      COMMENTS_MICROSERVICE_URL: 'http://localhost:8083/'
      SUPPORT_MICROSERVICE_URL: 'http://localhost:8084/'
    ports:
      - "8082:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_posts:/var/lib/postgresql/data/
    privileged: true
    restart: always
    environment:
      POSTGRES_DB: microblog_posts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass

volumes:
  postgres_posts:
