version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: microblog_comments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      DJANGO_SECRET_KEY: django-insecure-%7jp@b2=isop0hemkn*cv_!7v&xhwa-q52o9iz+3tlqrqw@^0@
      DJANGO_ENABLE_DEBUG: 1
      USERS_MICROSERVICE_URL: 'http://host.docker.internal:8080/'
      POSTS_MICROSERVICE_URL: 'http://host.docker.internal:8082/'
      COMMENTS_MICROSERVICE_URL: 'http://host.docker.internal:8083/'
      SUPPORT_MICROSERVICE_URL: 'http://host.docker.internal:8084/'
    ports:
      - "8083:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    privileged: true
    restart: always
    environment:
      POSTGRES_DB: microblog_comments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass

volumes:
  postgres_data:
