version: '3.8'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_posts:/var/lib/postgresql/data/
    privileged: true
    restart: always
    environment:
      POSTGRES_DB: microblog_posts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    ports:
      - "5432:5432"

volumes:
  postgres_posts:
